// Copyright (с) 2013 Gushcha Anton <ncrashed@gmail.com>
/*
* This file is part of Borey Engine.
*
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/
// This file is written in D programming language
/**
*   Borey Engine first example. It shows how to create window and
*   handle basic window events.
*/
module main;

import borey.core;
import borey.keyboard;
import borey.util.loader.loader;
import std.stdio;
import std.conv;

int main(string[] args)
{
    // Initializing core
    auto boreyCore = initBoreyCore();
    // Terminate when living main scope
    scope(exit) boreyCore.terminate();

    // Create window
    //auto window = boreyCore.createWindow(640, 480, "Test window");
    // Example for fullscreen
    auto window = boreyCore.createWindow(640, 480, "Test window", boreyCore.primaryMonitor());

    // Binding exit event
    window.keyboardDelegate =
        (win, state) @trusted
        {
            if(state.key == Key.ESCAPE) 
                boreyCore.shouldExit = true;
        };

    // Binding delegates for window events
    window.posChangedDelegate = 
        (win, x, y) @trusted => boreyCore.logger.logNotice(text("Window pos is now: (",x,",",y,")"));
    
    window.sizeChangedDelegate = 
        (win, width, height) @trusted => boreyCore.logger.logNotice(text("Window size is now: (", width, ",", height, ")"));
    
    window.framebufferSizeChangedDelegate =
        (win, width, height) @trusted => boreyCore.logger.logNotice(text("Window framebuffer size is now: (", width, ",", height, ")"));
   
    window.closeDelegate = 
        (win) @trusted => boreyCore.logger.logNotice(text("Window is closing!"));

    window.focusChangedDelegate = 
        (win, flag) @trusted => boreyCore.logger.logNotice(text("Window focused: ", flag));
    
    window.minimizedDelegate = 
        (win, flag) @trusted => boreyCore.logger.logNotice(text("Window iconified: ", flag));

    // Start infinite event-drawing loop
    boreyCore.runEventLoop();
    return 0;
}