// Copyright (с) 2013 Gushcha Anton <ncrashed@gmail.com>
/*
* This file is part of Borey Engine.
*
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/
// This file is written in D programming language
/**
*   Debug example, changes occasionally.
*/
module main;

import borey.core;
import borey.keyboard;
import borey.util.loader.loader;
import std.stdio;
import std.conv;

int main(string[] args)
{
    auto boreyCore = initBoreyCore();
    scope(exit) boreyCore.terminate();

    writeln(boreyCore.getVersion());
    writeln(boreyCore.copyright);
    writeln("Can engine handle many windows: ", boreyCore.supportManyWindows);

    boreyCore.logger.logNotice("Hi, it is test log message!");

    auto window = boreyCore.createWindow(640, 480, "Test window");

    // Binding exit event
    window.keyboardDelegate =
        (win, state) @trusted
        {
            if(state.key == Key.ESCAPE) 
                boreyCore.shouldExit = true;
        };

    // test
    window.charInputDelegate =
        (win, ch) @trusted => boreyCore.logger.logNotice(text("Unicode input: ", ch));

    window.cursorEnterDelegate = 
        (win, flag) @trusted => boreyCore.logger.logNotice(text("Cursor enters/leaving window: ", flag));

    window.cursorPosDelegate =
        (win, x, y) @trusted => boreyCore.logger.logNotice(text("Cursor position: ", x, ",", y));

    window.mouseButtonDelegate =
        (win, state) @trusted => boreyCore.logger.logNotice(text("Mouse button event: ", state.button, " pos: ", state.position));

    window.scrollDelegate =
        (win, xoffset, yoffset) @trusted => boreyCore.logger.logNotice(text("Scrolling event: ", xoffset, ",", yoffset));

    boreyCore.runEventLoop();
    return 0;
}