// Copyright (с) 2013 Gushcha Anton <ncrashed@gmail.com>
/*
* This file is part of Borey Engine.
*
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/
// This file is written in D programming language
module borey.resource.archive;

import borey.exception;
import borey.log;
import std.range;
import std.stream;
import std.conv;

/**
*   Thrown when loading of archive is failed.
*/
class ArchiveLoadingException : BoreyLoggedException
{
    /// Problem path
    string path;

    this(shared ILogger logger, string path, lazy string msg,
        string file = __FILE__, size_t line = __LINE__)
    {
        this.path = path;
        super(logger, text("[Archive]: Failed to load archive with path '", path, "'! Details: ", msg), file, line);
    }
}

/**
*   Thrown when trying to access not existing path
*   in archive.
*/
class PathIsNotExistsException : BoreyLoggedException
{
    /// Problem path
    string path;
    /// Problem archive
    IArchive archive;

    this(shared ILogger logger, IArchive archive, string path,
        string file = __FILE__, size_t line = __LINE__)
    {
        this.archive = archive;
        this.path = path;
        super(logger, text("Path '",path," is not exists in archive '",archive.name,"'"), file, line);
    }
}

/**
*   Thrown when trying to access not existing path
*   in archive.
*/
class UnsupportedReadException : BoreyLoggedException
{
    /// Problem archive
    IArchive archive;

    this(shared ILogger logger, IArchive archive,
        string file = __FILE__, size_t line = __LINE__)
    {
        this.archive = archive;
        super(logger, text("Archive '",archive.name,"' doesn't support read access!"), file, line);
    }
}

/**
*   Thrown when trying to access not existing path
*   in archive.
*/
class UnsupportedWriteException : BoreyLoggedException
{
    /// Problem archive
    IArchive archive;

    this(shared ILogger logger, IArchive archive,
        string file = __FILE__, size_t line = __LINE__)
    {
        this.archive = archive;
        super(logger, text("Archive '",archive.name,"' doesn't support write access!"), file, line);
    }
}

/**
*   Thrown when trying to access not existing path
*   in archive.
*/
class FileConflictException : BoreyLoggedException
{
    /// Problem path
    string path;
    /// Problem archive
    IArchive archive;

    this(shared ILogger logger, IArchive archive, string path,
        string file = __FILE__, size_t line = __LINE__)
    {
        this.path = path;
        this.archive = archive;
        super(logger, text("Found another file at '", path,"' in archive '",archive.name,"'!"), file, line);
    }
}

/**
*   Describes container object, which can extract/insert
*   resources. Archive can be a file system, zip archive
*   or remote ftp server.
*/
interface IArchive
{
    /// Returns name of archive
    string name() const @property;

    /// Returns true if archive can read resources
    bool readable() const @property;

    /// Returns true if archive can write resources
    bool writeable() const @property;

    /**
    *   Returns range of available files in archive.
    *
    *   Params:
    *   prefix = path to find from, if specified path is not
    *           exists in archive throws exception PathIsNotExistsException.
    *   recurse = if true will list also all subdirectories.
    */
    InputRange!string getAvaiableFiles(string prefix = "/", bool recurse = true);

    /**
    *   Checks file existance in archive with specified fullName without extensions.
    *   Note: Function can find more than one file with same extension.
    *
    *   Params:
    *   fullName =  File name without extension.
    *   extensions = There method will write finded files extensions.
    *
    *   Returns: true if file is located in the archive.
    */
    bool hasFile(string fullName, out string[] extensions);

    /**
    *   If file with name fullName is exists, returns stream to read it,
    *   else throws exception PathIsNotExistsException.
    *   
    *   Should throw UnsupportedReadException if readable property is set to false.
    *
    *   Throws: PathIsNotExistsException, UnsupportedReadException, PackSecurityException
    */
    InputStream read(string fullName);

    /**
    *   If archive supports writing, writes content of stream into it.
    *   Should automatically create all needed directories.
    *   If replace is set to false and another file is located at fullName,
    *   should throw FileConflictException.
    *
    *   Throws: UnsupportedWriteException, FileConflictException, PackSecurityException
    */
    void write(string fullName, Stream stream, bool replace = false);
}