// Copyright (с) 2013 Gushcha Anton <ncrashed@gmail.com>
/*
* This file is part of Borey Engine.
*
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/
// This file is written in D programming language
/**
*   Module provides derelict style loader for Borey Engine implementation.
*
*   Example demonstates low-level way to load implementation lib with
*   setting garbage collector proxy. Application will use the shared lib
*   gc.
*
*   Example:
*   -------
*   extern(C) 
*   {
*       void gc_setProxy(void* p); 
*       void gc_clrProxy(); 
*   }
*
*   void loadEngine()
*   {
*      DerelictBorey.load(); // loads implementation lib
*       
*      gc_setProxy(boreyEngineInitialize()); // sets proxy for library
*      
*      // unloading library
*      gc_clrProxy();
*      boreyEngineTerminate();
*
*      DerelictBorey.unload(); // optional, will be called when terminating application
*   }
*   -------
*/
module borey.util.loader.loader;
@trusted:

public import borey.util.loader.functions;
import borey.core;

version(BOREY_DYNAMIC_LOADING)
{
    import borey.exception;
    import std.conv;

    private
    {
        import derelict.util.loader;
        import derelict.util.system;
        import derelict.util.exception;

        static if(Derelict_OS_Windows)
            enum libNames = "borey-engine.dll";
        else static if(Derelict_OS_Posix)
            enum libNames = "libborey-engine.so, ./libborey-engine.so";
        else
            static assert(0, "Need to implement Borey Engine libNames for this operating system.");
    }

    class BoreyEngineLoader : SharedLibLoader
    {
        protected
        {
            override void loadSymbols()
            {
                try
                {
                    bindFunc(cast(void**)&boreyEngineInitialize, "boreyEngineInitialize");
                    bindFunc(cast(void**)&boreyEngineTerminate, "boreyEngineTerminate");
                    bindFunc(cast(void**)&createBoreyCore, "createBoreyCore");
                } 
                catch(DerelictException e)
                {
                    throw new BoreyException(text("Failed to load Borey Engine implementation! Details: ", e.msg));
                }
            }
        }

        public
        {
            this()
            {
                super(libNames);
            }
        }
    }

    __gshared BoreyEngineLoader DerelictBorey;

    shared static this()
    {
        DerelictBorey = new BoreyEngineLoader();
    }

    private
    {
        import borey.util.loader.loader;
        import core.atomic;

        shared bool isCoreLoaded = false;

        extern(C) 
        {
           void gc_setProxy(void* p); 
           void gc_clrProxy(); 
        }
    }

    /**
    *   Loads implementaton lib and queries core with specified characteristics.
    *   Note: concurrency safe.
    */
    IBoreyCore initBoreyCore() @trusted
    {
        if(!atomicLoad(isCoreLoaded)) 
        {
            DerelictBorey.load(); // loads implementation lib
            gc_setProxy(boreyEngineInitialize()); // sets proxy for library
            atomicStore(isCoreLoaded, true);
        }

        return createBoreyCore();
    }

    shared static ~this()
    {
        if(cas(&isCoreLoaded, true, false))
        {
            // unloading library
            gc_clrProxy();
            boreyEngineTerminate();        
        }
        DerelictBorey.unload();
    }
}
else
{
    /**
    *   Loads implementaton lib and queries core with specified characteristics.
    *   Note: concurrency safe.
    */
    IBoreyCore initBoreyCore() @trusted
    {
        return createBoreyCore();
    }

    shared static this()
    {
        boreyEngineInitialize();
    }

    shared static ~this()
    {
        boreyEngineTerminate();
    }
}