// Copyright (с) 2013 Gushcha Anton <ncrashed@gmail.com>
/*
* This file is part of Borey Engine.
*
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/
// This file is written in D programming language
module borey.scene.node;
@safe:

import borey.util.vector;
import borey.util.quaternion;
import std.range;

/**
*   Scene node incapsulates position information about scene
*   objects. Each node handles releative position and rotation,
*   absolute position and rotation can be extracted by descenging
*   scene graph and accumulating releative attributes.
*
*   Scene nodes aren't created explicity, you should use
*   createChild method to attach new node to another. Scene manager
*   always has root scene node to attach to.
*/
interface ISceneNode
{
    synchronized
    {
        /**
        *   Returns scene node name to accessing by name.
        */
        string name() const @property;

        /**
        *   Returns node parent, or null to root scene node 
        *   (special case is detached scene node which won't be drawed).
        */
        shared(ISceneNode) parent() @property;

        /**
        *   Setting node parent. Does not remove node from
        *   children list of parent! 
        *
        *   See_Also: detachChild, attachChild for user code.
        */
        void parent(shared ISceneNode node) @property;

        /**
        *   Returns range of attached children.
        */
        InputRange!(shared ISceneNode) children() @property;

        /**
        *   Performing search of scene node by name, if recurse
        *   parameter is true, search will be recursive up to
        *   leafs of scene tree.
        *
        *   Returns: Range of finded nodes.
        */
        InputRange!(shared ISceneNode) find(string name, bool recurse = true);

        /**
        *   Creates child node with name. Setups default position and rotation.
        */
        shared(ISceneNode) createChild(string name, vector3df pos = vector3df.ZERO, Quaternion rot = Quaternion.UNIT);

        /**
        *   Detaches scene node from parent.
        *   
        *   Note: to make node invisible, use visble property.
        *   Note: If node is not attached, does nothing.
        */
        void detachChild(shared ISceneNode node);

        /**
        *   Attaches child scene node to this node.
        *
        *   Note: to make node invisible, use visble property.
        *   Note: if node already attached, does nothing.
        */
        void attachChild(shared ISceneNode node);

        /**
        *   If node is not visible, it won't be drawed as all it children.
        */
        bool visible() const @property;

        /**
        *   If node is not visible, it won't be drawed as all it children.
        */
        void visble(bool value) @property;

        /**
        *   Returns node local (relative the parent) position.
        */
        vector3df position() const @property;

        /**
        *   Sets node local position (relative the parent).
        */
        void position(vector3df val) @property;

        /**
        *   Return node local rotation (relative the parent).
        */
        Quaternion rotation() const @property;

        /**
        *   Sets node local rotation (relative the parent).
        */
        void rotation(Quaternion val) @property;

        /**
        *   Returns absolute location (relative the root node).
        */
        vector3df absolutePosition() const @property;

        /**
        *   Returns absolute roatation (relative the root node).
        */
        Quaternion absoluteRotation() const @property;
    }
}